apiVersion: v1
kind: Service
metadata:
  name: raft # Nombre del servicio
  labels:
    app: rep # Etiqueta para identificar el servicio
spec:
  clusterIP: None
  selector:      # tiene que coincidir con label definido en pod de StatefulSet
    app: rep  # Para dar de alta automaticamente en DNS a los PODS ligados
  ports:
  - port: 6000  # Puerto expuesto por el servicio
    name: servidor-port  # Nombre del puerto, útil para referencias internas
    protocol: TCP  # Protocolo de comunicación (TCP)
    targetPort: 6000  # Puerto en los Pods donde el tráfico será redirigido

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nodo  # Nombre del StatefulSet
spec:
  serviceName: raft  # Asociar este StatefulSet al Headless Service "raft"
  replicas: 3  # Número de réplicas o nodos en el StatefulSet
  podManagementPolicy: Parallel  # Crear y administrar Pods en paralelo (no secuencialmente)
  selector:
    matchLabels:
      app: rep  # Debe coincidir con las etiquetas definidas en el template de los Pods
  template:
    metadata:
      labels:
        app: rep  # Etiqueta que asocia los Pods al Headless Service
    spec:
      terminationGracePeriodSeconds: 10  # Tiempo de espera antes de forzar la terminación del Pod
      containers:
      - name: servidor  # Nombre del contenedor dentro del Pod
        image: localhost:5001/servidor:latest  # Imagen del contenedor a utilizar
        env:
        - name: MISUBDOMINIODNS  # Variable de entorno para el dominio del servicio
          value: raft.default.svc.cluster.local  # Dominio completo del servicio headless
        - name: MINOMBREPOD  # Variable de entorno que almacena el nombre del Pod
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # Asigna dinámicamente el nombre del Pod
        command:
        - servidor  # Comando principal del contenedor
        - $(MINOMBREPOD)  # Pasa el nombre del Pod como parámetro al comando
        ports:
        - containerPort: 6000  # Puerto expuesto por el contenedor
---
# Definición del cliente
apiVersion: v1
kind: Pod
metadata:
  name: client  # Nombre del Pod cliente
spec:
  restartPolicy: Never  # El Pod no será reiniciado si falla
  containers:
  - name: cliente  # Nombre del contenedor dentro del Pod
    image: localhost:5001/cliente:latest  # Imagen del contenedor a ejecutar
    command: 
    - cliente  # Comando principal que ejecutará el contenedor
    ports:
    - containerPort: 7000  # Puerto expuesto por el contenedor
  

